model:
  name: base_transformers
  provider: transformers
  pretrained_model_name_or_path: Qwen/Qwen2-1.5B-Instruct
  torch_dtype: auto
  trust_remote_code: false
  load_in_8bit: false
  load_in_4bit: false
